import "server-only";
import type { Company } from "./schema";

/**
 * Local fixtures used when `NOTION_TOKEN` is not set. Lets the app render
 * meaningfully during local dev without a Notion integration token.
 *
 * The moment NOTION_TOKEN lands in env, the live Notion fetch takes over
 * and these fixtures are bypassed.
 */
export const FIXTURE_COMPANIES: Company[] = [
  {
    id: "fx-acme-governance",
    company: "Acme Governance",
    slug: "acme-governance",
    thesis: "Governed Agentic Ops",
    sector: "FinServices AI",
    stage: "Seed",
    hq: "London, UK",
    headcount: 18,
    founded: 2024,
    lastRaise: "€7.5M seed led by Mouro Capital",
    ssiScore: 87,
    signalTier: "🔴 Highest Conviction",
    priority: "P0",
    discoverySource: "regscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    sourceConfidence: "High",
    oneLiner: "Runtime governance for autonomous workflows in regulated finance.",
    keySignal30d: "DORA-aligned audit pack shipped 4 Apr 2026.",
    catalystWindowDays: 0,
    lastVerified: "2026-05-19",
    lastScored: "2026-05-18",
    signals: ["s1", "s2", "s3", "s4", "s5"],
    primaryCatalyst: "cat-dora",
    marketMapSubSegment: "mm-gao-banking",
    lastSignalDate: "2026-05-19",
  },
  {
    id: "fx-lattice-dev",
    company: "Lattice Dev",
    slug: "lattice-dev",
    thesis: "Vertical SoR AI",
    sector: "MedTech AI",
    stage: "Series A",
    hq: "Munich, DE",
    headcount: 34,
    founded: 2023,
    lastRaise: "€15M Series A led by HV Capital",
    ssiScore: 81,
    signalTier: "🔴 Highest Conviction",
    priority: "P0",
    discoverySource: "ghscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    sourceConfidence: "High",
    oneLiner: "System of record for hospital procurement decisions, EHDS-native.",
    keySignal30d: "Charité signed 12 Mar 2026.",
    catalystWindowDays: 14,
    lastVerified: "2026-05-15",
    lastScored: "2026-05-10",
    signals: ["s10", "s11", "s12", "s13"],
    primaryCatalyst: "cat-ehds",
    marketMapSubSegment: "mm-vsr-medtech",
    lastSignalDate: "2026-05-17",
  },
  {
    id: "fx-redflag-co",
    company: "Redflag Co",
    slug: "redflag-co",
    thesis: "Vertical SoR AI",
    sector: "Insurance AI",
    stage: "Pre-Seed",
    hq: "Berlin, DE",
    headcount: 6,
    founded: 2025,
    lastRaise: "€500k angel",
    ssiScore: 62,
    signalTier: "🟡 Emerging",
    priority: "P2",
    discoverySource: "manual",
    falsifierCheck: "❌ Triggered",
    antithesisFilter: "Clear",
    sourceConfidence: "Low",
    oneLiner: "Claims triage agent. Falsifier triggered on synthetic-data dependency.",
    keySignal30d: "",
    catalystWindowDays: null,
    lastVerified: "2026-01-02",
    lastScored: "2026-01-02",
    signals: [],
    primaryCatalyst: null,
    marketMapSubSegment: null,
    lastSignalDate: "2026-01-02",
  },
  {
    id: "fx-clausel",
    company: "Clausel",
    slug: "clausel",
    thesis: "Vertical SoR AI",
    sector: "Legal AI",
    stage: "Seed",
    hq: "Paris, FR",
    headcount: 12,
    founded: 2024,
    lastRaise: "€4.2M seed led by Singular",
    ssiScore: 78,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "procscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    sourceConfidence: "High",
    oneLiner: "Contract writeback for European M&A workflows.",
    keySignal30d: "Bredin Prat live integration 22 Apr 2026.",
    catalystWindowDays: 60,
    lastVerified: "2026-05-12",
    lastScored: "2026-05-12",
    signals: ["s20", "s21"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-vsr-legal",
    lastSignalDate: "2026-05-12",
  },
  {
    id: "fx-helix-eval",
    company: "Helix Eval",
    slug: "helix-eval",
    thesis: "Governed Agentic Ops",
    sector: "Eval Infra",
    stage: "Seed",
    hq: "Amsterdam, NL",
    headcount: 9,
    founded: 2024,
    lastRaise: "€3M seed led by Cherry",
    ssiScore: 73,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "ghscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    sourceConfidence: "Medium",
    oneLiner: "Continuous evaluation for production LLM agents under EU AI Act Annex III.",
    keySignal30d: "ING pilot kicked off 8 May 2026.",
    catalystWindowDays: 21,
    lastVerified: "2026-05-10",
    lastScored: "2026-05-08",
    signals: ["s30", "s31", "s32"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-gao-eval",
    lastSignalDate: "2026-05-15",
  },
  {
    id: "fx-pillar-ops",
    company: "Pillar Ops",
    slug: "pillar-ops",
    thesis: "Governed Agentic Ops",
    sector: "AI Governance",
    stage: "Pre-Seed",
    hq: "Bucharest, RO",
    headcount: 5,
    founded: 2025,
    lastRaise: "€800k pre-seed",
    ssiScore: 68,
    signalTier: "🟡 Emerging",
    priority: "P2",
    discoverySource: "talentscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    sourceConfidence: "Medium",
    oneLiner: "Policy-as-code for agent runtime governance.",
    keySignal30d: "Ex-ANCOM technical lead joined 1 May 2026.",
    catalystWindowDays: 90,
    lastVerified: "2026-05-04",
    lastScored: "2026-05-04",
    signals: ["s40", "s41"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-gao-policy",
    lastSignalDate: "2026-05-04",
  },
  {
    id: "fx-substrate-fr",
    company: "Substrate FR",
    slug: "substrate-fr",
    thesis: "Both",
    sector: "Defence AI",
    stage: "Series A",
    hq: "Paris, FR",
    headcount: 41,
    founded: 2022,
    lastRaise: "€22M Series A led by Eurazeo",
    ssiScore: 79,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "grantscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    sourceConfidence: "High",
    oneLiner: "Audit-grade autonomous ops with vertical SoR for defence procurement.",
    keySignal30d: "DGA framework contract executed 17 Apr 2026.",
    catalystWindowDays: 30,
    lastVerified: "2026-05-17",
    lastScored: "2026-05-16",
    signals: ["s50", "s51", "s52", "s53"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-both-defence",
    lastSignalDate: "2026-05-17",
  },
  {
    id: "fx-cogni-care",
    company: "CogniCare",
    slug: "cognicare",
    thesis: "Vertical SoR AI",
    sector: "Healthcare AI",
    stage: "Seed",
    hq: "Stockholm, SE",
    headcount: 14,
    founded: 2024,
    lastRaise: "€5M seed led by EQT Ventures",
    ssiScore: 71,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "spinoutscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    sourceConfidence: "High",
    oneLiner: "Clinical notes system-of-record, native to MDR audit trails.",
    keySignal30d: "Karolinska live 28 Mar 2026.",
    catalystWindowDays: 45,
    lastVerified: "2026-05-08",
    lastScored: "2026-05-07",
    signals: ["s60", "s61"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-vsr-healthcare",
    lastSignalDate: "2026-05-08",
  },
  {
    id: "fx-watchtower",
    company: "Watchtower",
    slug: "watchtower",
    thesis: "Governed Agentic Ops",
    sector: "AI Governance",
    stage: "Seed",
    hq: "Tallinn, EE",
    headcount: 11,
    founded: 2024,
    lastRaise: "€2.8M seed led by Speedinvest",
    ssiScore: 75,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "regscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    sourceConfidence: "High",
    oneLiner: "Real-time audit pack for cross-border agent operations.",
    keySignal30d: "RegTech Award shortlist Feb 2026.",
    catalystWindowDays: 18,
    lastVerified: "2026-05-13",
    lastScored: "2026-05-13",
    signals: ["s70", "s71", "s72"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-gao-audit",
    lastSignalDate: "2026-05-16",
  },
  {
    id: "fx-orgaize",
    company: "Orgaize",
    slug: "orgaize",
    thesis: "Vertical SoR AI",
    sector: "Workflow Infra",
    stage: "Pre-Seed",
    hq: "Lisbon, PT",
    headcount: 4,
    founded: 2025,
    lastRaise: "€600k angel",
    ssiScore: 58,
    signalTier: "⚪ Watchlist",
    priority: "P3",
    discoverySource: "manual",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    sourceConfidence: "Low",
    oneLiner: "Workflow SoR for SME logistics.",
    keySignal30d: "",
    catalystWindowDays: null,
    lastVerified: "2025-12-15",
    lastScored: "2025-12-15",
    signals: [],
    primaryCatalyst: null,
    marketMapSubSegment: null,
    lastSignalDate: "2025-12-15",
  },
];
