import "server-only";
import type { Company, Signal } from "./schema";

/**
 * Local fixtures used as the demo dataset until the live Notion SSI v3.0 rubric
 * is actually scored. Served when NOTION_TOKEN is missing, when forced via
 * PORTRAITS_FORCE_FIXTURES, or while no live company has a score yet (see
 * lib/notion/companies.ts). Once the Scouting Engine fills scores in, the live
 * fetch takes over automatically.
 *
 * gaoDims / vsraiDims are left null so the portrait uses its synthetic vector,
 * keeping these fixtures visually identical to Phase 1.
 */
export const FIXTURE_COMPANIES: Company[] = [
  {
    id: "fx-acme-governance",
    company: "Acme Governance",
    slug: "acme-governance",
    thesis: "Governed Agentic Ops",
    hqCountry: ["United Kingdom"],
    stage: "Seed",
    headcount: 18,
    founded: 2024,
    lastRaise: "€7.5M seed led by Mouro Capital",
    ssiScore: 87,
    signalTier: "🔴 Highest Conviction",
    priority: "P0",
    discoverySource: "regscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    status: "📊 Scored",
    oneLiner: "Runtime governance for autonomous workflows in regulated finance.",
    keySignal30d: "DORA-aligned audit pack shipped 4 Apr 2026.",
    catalystWindowDays: 0,
    lastVerified: "2026-05-19",
    lastScored: "2026-05-18",
    signals: ["s1", "s2", "s3", "s4", "s5"],
    primaryCatalyst: "cat-dora",
    marketMapSubSegment: "mm-gao-banking",
    lastSignalDate: "2026-05-19",
    gaoDims: null,
    vsraiDims: null,
  },
  {
    id: "fx-lattice-dev",
    company: "Lattice Dev",
    slug: "lattice-dev",
    thesis: "Vertical SoR AI",
    hqCountry: ["Germany"],
    stage: "Series A",
    headcount: 34,
    founded: 2023,
    lastRaise: "€15M Series A led by HV Capital",
    ssiScore: 81,
    signalTier: "🔴 Highest Conviction",
    priority: "P0",
    discoverySource: "ghscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    status: "📊 Scored",
    oneLiner: "System of record for hospital procurement decisions, EHDS-native.",
    keySignal30d: "Charité signed 12 Mar 2026.",
    catalystWindowDays: 14,
    lastVerified: "2026-05-15",
    lastScored: "2026-05-10",
    signals: ["s10", "s11", "s12", "s13"],
    primaryCatalyst: "cat-ehds",
    marketMapSubSegment: "mm-vsr-medtech",
    lastSignalDate: "2026-05-17",
    gaoDims: null,
    vsraiDims: null,
  },
  {
    id: "fx-redflag-co",
    company: "Redflag Co",
    slug: "redflag-co",
    thesis: "Vertical SoR AI",
    hqCountry: ["Germany"],
    stage: "Pre-Seed",
    headcount: 6,
    founded: 2025,
    lastRaise: "€500k angel",
    ssiScore: 62,
    signalTier: "🟡 Emerging",
    priority: "P2",
    discoverySource: "manual",
    falsifierCheck: "❌ Triggered",
    antithesisFilter: "Clear",
    status: "🔍 Research",
    oneLiner: "Claims triage agent. Falsifier triggered on synthetic-data dependency.",
    keySignal30d: "",
    catalystWindowDays: null,
    lastVerified: "2026-01-02",
    lastScored: "2026-01-02",
    signals: [],
    primaryCatalyst: null,
    marketMapSubSegment: null,
    lastSignalDate: "2026-01-02",
    gaoDims: null,
    vsraiDims: null,
  },
  {
    id: "fx-clausel",
    company: "Clausel",
    slug: "clausel",
    thesis: "Vertical SoR AI",
    hqCountry: ["France"],
    stage: "Seed",
    headcount: 12,
    founded: 2024,
    lastRaise: "€4.2M seed led by Singular",
    ssiScore: 78,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "procscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    status: "📊 Scored",
    oneLiner: "Contract writeback for European M&A workflows.",
    keySignal30d: "Bredin Prat live integration 22 Apr 2026.",
    catalystWindowDays: 60,
    lastVerified: "2026-05-12",
    lastScored: "2026-05-12",
    signals: ["s20", "s21"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-vsr-legal",
    lastSignalDate: "2026-05-12",
    gaoDims: null,
    vsraiDims: null,
  },
  {
    id: "fx-helix-eval",
    company: "Helix Eval",
    slug: "helix-eval",
    thesis: "Governed Agentic Ops",
    hqCountry: ["Netherlands"],
    stage: "Seed",
    headcount: 9,
    founded: 2024,
    lastRaise: "€3M seed led by Cherry",
    ssiScore: 73,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "ghscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    status: "📊 Scored",
    oneLiner: "Continuous evaluation for production LLM agents under EU AI Act Annex III.",
    keySignal30d: "ING pilot kicked off 8 May 2026.",
    catalystWindowDays: 21,
    lastVerified: "2026-05-10",
    lastScored: "2026-05-08",
    signals: ["s30", "s31", "s32"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-gao-eval",
    lastSignalDate: "2026-05-15",
    gaoDims: null,
    vsraiDims: null,
  },
  {
    id: "fx-pillar-ops",
    company: "Pillar Ops",
    slug: "pillar-ops",
    thesis: "Governed Agentic Ops",
    hqCountry: ["Romania"],
    stage: "Pre-Seed",
    headcount: 5,
    founded: 2025,
    lastRaise: "€800k pre-seed",
    ssiScore: 68,
    signalTier: "🟡 Emerging",
    priority: "P2",
    discoverySource: "talentscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    status: "📊 Scored",
    oneLiner: "Policy-as-code for agent runtime governance.",
    keySignal30d: "Ex-ANCOM technical lead joined 1 May 2026.",
    catalystWindowDays: 90,
    lastVerified: "2026-05-04",
    lastScored: "2026-05-04",
    signals: ["s40", "s41"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-gao-policy",
    lastSignalDate: "2026-05-04",
    gaoDims: null,
    vsraiDims: null,
  },
  {
    id: "fx-substrate-fr",
    company: "Substrate FR",
    slug: "substrate-fr",
    thesis: "Both",
    hqCountry: ["France"],
    stage: "Series A",
    headcount: 41,
    founded: 2022,
    lastRaise: "€22M Series A led by Eurazeo",
    ssiScore: 79,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "grantscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    status: "📊 Scored",
    oneLiner: "Audit-grade autonomous ops with vertical SoR for defence procurement.",
    keySignal30d: "DGA framework contract executed 17 Apr 2026.",
    catalystWindowDays: 30,
    lastVerified: "2026-05-17",
    lastScored: "2026-05-16",
    signals: ["s50", "s51", "s52", "s53"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-both-defence",
    lastSignalDate: "2026-05-17",
    gaoDims: null,
    vsraiDims: null,
  },
  {
    id: "fx-cogni-care",
    company: "CogniCare",
    slug: "cognicare",
    thesis: "Vertical SoR AI",
    hqCountry: ["Sweden"],
    stage: "Seed",
    headcount: 14,
    founded: 2024,
    lastRaise: "€5M seed led by EQT Ventures",
    ssiScore: 71,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "spinoutscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    status: "📊 Scored",
    oneLiner: "Clinical notes system-of-record, native to MDR audit trails.",
    keySignal30d: "Karolinska live 28 Mar 2026.",
    catalystWindowDays: 45,
    lastVerified: "2026-05-08",
    lastScored: "2026-05-07",
    signals: ["s60", "s61"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-vsr-healthcare",
    lastSignalDate: "2026-05-08",
    gaoDims: null,
    vsraiDims: null,
  },
  {
    id: "fx-watchtower",
    company: "Watchtower",
    slug: "watchtower",
    thesis: "Governed Agentic Ops",
    hqCountry: ["Estonia"],
    stage: "Seed",
    headcount: 11,
    founded: 2024,
    lastRaise: "€2.8M seed led by Speedinvest",
    ssiScore: 75,
    signalTier: "🟠 Strong",
    priority: "P1",
    discoverySource: "regscan",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    status: "📊 Scored",
    oneLiner: "Real-time audit pack for cross-border agent operations.",
    keySignal30d: "RegTech Award shortlist Feb 2026.",
    catalystWindowDays: 18,
    lastVerified: "2026-05-13",
    lastScored: "2026-05-13",
    signals: ["s70", "s71", "s72"],
    primaryCatalyst: null,
    marketMapSubSegment: "mm-gao-audit",
    lastSignalDate: "2026-05-16",
    gaoDims: null,
    vsraiDims: null,
  },
  {
    id: "fx-orgaize",
    company: "Orgaize",
    slug: "orgaize",
    thesis: "Vertical SoR AI",
    hqCountry: ["Portugal"],
    stage: "Pre-Seed",
    headcount: 4,
    founded: 2025,
    lastRaise: "€600k angel",
    ssiScore: 58,
    signalTier: "⚪ Watchlist",
    priority: "P3",
    discoverySource: "manual",
    falsifierCheck: "✅ Clean",
    antithesisFilter: "Clear",
    status: "🔍 Research",
    oneLiner: "Workflow SoR for SME logistics.",
    keySignal30d: "",
    catalystWindowDays: null,
    lastVerified: "2025-12-15",
    lastScored: "2025-12-15",
    signals: [],
    primaryCatalyst: null,
    marketMapSubSegment: null,
    lastSignalDate: "2025-12-15",
    gaoDims: null,
    vsraiDims: null,
  },
];

/**
 * Local signal fixtures keyed by the parent companyId. Used by
 * fetchSignalsFor when serving fixtures so the detail-page timeline
 * has something meaningful to render.
 */
export const FIXTURE_SIGNALS: Record<string, Signal[]> = {
  "fx-acme-governance": [
    {
      id: "s1",
      title: "DORA audit pack v2.1 shipped",
      signalType: "Product",
      signalStrength: "High",
      evidenceQuality: "Verified",
      sourceUrl: "https://acmegov.example/changelog/v2.1",
      dateDetected: "2026-05-19",
      signalDate: "2026-05-19",
      detail: "Public changelog adds Article 6 evidence export.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-acme-governance",
    },
    {
      id: "s2",
      title: "Ex-DNB head of model risk joined as VP Eng",
      signalType: "Hire",
      signalStrength: "High",
      evidenceQuality: "Verified",
      sourceUrl: "https://www.linkedin.com/in/example",
      dateDetected: "2026-05-04",
      signalDate: "2026-05-04",
      detail: "10 years at the Dutch central bank; signed compliance lead.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-acme-governance",
    },
    {
      id: "s3",
      title: "EU AI Office consultation submission",
      signalType: "Regulatory",
      signalStrength: "Medium",
      evidenceQuality: "Verified",
      sourceUrl: "https://digital-strategy.ec.europa.eu/example",
      dateDetected: "2026-04-22",
      signalDate: "2026-04-22",
      detail: "Submitted feedback on Annex III code-of-practice.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-acme-governance",
    },
    {
      id: "s4",
      title: "€7.5M seed announced",
      signalType: "Funding",
      signalStrength: "High",
      evidenceQuality: "Verified",
      sourceUrl: "https://techcrunch.example/acme-seed",
      dateDetected: "2026-04-12",
      signalDate: "2026-04-12",
      detail: "Mouro Capital lead; EIC Accelerator co-invest.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-acme-governance",
    },
    {
      id: "s5",
      title: "CEN-CENELEC JTC 21 working-group contribution",
      signalType: "Regulatory",
      signalStrength: "Medium",
      evidenceQuality: "Verified",
      sourceUrl: null,
      dateDetected: "2026-03-28",
      signalDate: "2026-03-28",
      detail: "Listed as co-author on draft standard.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-acme-governance",
    },
  ],
  "fx-lattice-dev": [
    {
      id: "s10",
      title: "Public commit: agent-trace OTEL exporter",
      signalType: "Product",
      signalStrength: "High",
      evidenceQuality: "Verified",
      sourceUrl: "https://github.com/lattice/example",
      dateDetected: "2026-05-15",
      signalDate: "2026-05-15",
      detail: "OpenTelemetry-compatible trace exporter for agent runs.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-lattice-dev",
    },
    {
      id: "s11",
      title: "Named pilot with major NL bank",
      signalType: "Buyer",
      signalStrength: "High",
      evidenceQuality: "Verified",
      sourceUrl: null,
      dateDetected: "2026-04-30",
      signalDate: "2026-04-30",
      detail: "Press release names the bank and the scope.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-lattice-dev",
    },
    {
      id: "s12",
      title: "HITL escalation API public",
      signalType: "Product",
      signalStrength: "Medium",
      evidenceQuality: "Verified",
      sourceUrl: null,
      dateDetected: "2026-04-08",
      signalDate: "2026-04-08",
      detail: "Documented human-in-the-loop API in the public docs.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-lattice-dev",
    },
  ],
  "fx-substrate-fr": [
    {
      id: "s20",
      title: "AMF sandbox graduation",
      signalType: "Regulatory",
      signalStrength: "High",
      evidenceQuality: "Verified",
      sourceUrl: "https://amf-france.example",
      dateDetected: "2026-05-10",
      signalDate: "2026-05-10",
      detail: "Graduated from the French market regulator's sandbox program.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-substrate-fr",
    },
    {
      id: "s21",
      title: "Bpifrance follow-on lead",
      signalType: "Funding",
      signalStrength: "Medium",
      evidenceQuality: "Verified",
      sourceUrl: null,
      dateDetected: "2026-04-18",
      signalDate: "2026-04-18",
      detail: "Follow-on round signal in Bpifrance portfolio update.",
      verified: true,
      disqualifying: false,
      pipelineCompany: "fx-substrate-fr",
    },
  ],
};
